#!/usr/bin/env bash
# ai/init.sh - Bootstrap script for agent-foreman harness
# Generated by agent-foreman
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

# Bootstrap: Install dependencies
bootstrap() {
  log_info "Installing dependencies..."
  npm install
  log_info "Bootstrap complete!"
}

# Dev: Start development environment
dev() {
  log_info "Starting development server..."
  npm run dev
}

# Check: Run all verification checks (tests, types, lint, build, e2e)
# Usage: check [--quick] [--full] [--skip-e2e] [test_pattern]
# Environment: E2E_TAGS - comma-separated tags for E2E filtering in quick mode
check() {
  local exit_code=0
  local e2e_exit_code=0
  local quick_mode=false
  local full_mode=false
  local skip_e2e=false
  local test_pattern=""
  local e2e_tags="${E2E_TAGS:-}"

  # Parse arguments
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --quick)
        quick_mode=true
        shift
        ;;
      --full)
        full_mode=true
        shift
        ;;
      --skip-e2e)
        skip_e2e=true
        shift
        ;;
      *)
        test_pattern="$1"
        shift
        ;;
    esac
  done

  if [ "$full_mode" = true ]; then
    log_info "Running checks (full mode)..."
  elif [ "$quick_mode" = true ]; then
    log_info "Running checks (quick mode)..."
  else
    log_info "Running checks..."
  fi

  # Run unit tests if available
  # CI=true disables watch mode in Vitest/Jest and ensures single-run execution
  log_warn "No test command configured"

  # In quick mode, skip type check, lint, and build
  if [ "$quick_mode" = true ]; then
    log_info "Quick mode: skipping type check, lint, and build"
  else
    # Run type check if TypeScript detected
    if [ -f "tsconfig.json" ]; then
      log_info "Running type check..."
      if ! npx tsc --noEmit; then
        log_error "Type check failed"
        exit_code=1
      fi
    fi

    # Run lint if available
    

    # Run build if available
    
  fi

  # Run E2E tests (after unit tests)
  # No E2E tests configured

  # Report final status
  if [ $exit_code -eq 0 ] && [ $e2e_exit_code -eq 0 ]; then
    log_info "All checks passed!"
  else
    if [ $exit_code -ne 0 ]; then
      log_error "Unit tests/checks failed"
    fi
    if [ $e2e_exit_code -ne 0 ]; then
      log_error "E2E tests failed"
    fi
  fi

  # Return combined exit code
  return $(( exit_code + e2e_exit_code ))
}

# Build: Build for production
build() {
  log_info "Building for production..."
  echo 'No build command configured'
  log_info "Build complete!"
}

# Status: Show project status
status() {
  log_info "Project Status"
  echo "---"

  # Show feature list status if exists (check new format first, then legacy)
  if [ -f "ai/features/index.json" ]; then
    echo "Feature Index: ai/features/index.json"
    local total=$(jq '.features | keys | length' ai/features/index.json)
    local passing=$(jq '[.features | to_entries[] | select(.value.status == "passing")] | length' ai/features/index.json)
    local failing=$(jq '[.features | to_entries[] | select(.value.status == "failing")] | length' ai/features/index.json)
    local review=$(jq '[.features | to_entries[] | select(.value.status == "needs_review")] | length' ai/features/index.json)
    echo "  Total: $total"
    echo "  Passing: $passing"
    echo "  Failing: $failing"
    echo "  Needs Review: $review"
  elif [ -f "ai/feature_list.json" ]; then
    echo "Feature List (legacy): ai/feature_list.json"
    local total=$(jq '.features | length' ai/feature_list.json)
    local passing=$(jq '[.features[] | select(.status == "passing")] | length' ai/feature_list.json)
    local failing=$(jq '[.features[] | select(.status == "failing")] | length' ai/feature_list.json)
    local review=$(jq '[.features[] | select(.status == "needs_review")] | length' ai/feature_list.json)
    echo "  Total: $total"
    echo "  Passing: $passing"
    echo "  Failing: $failing"
    echo "  Needs Review: $review"
  else
    log_warn "No feature list found. Run 'agent-foreman init' first."
  fi

  # Show recent progress log entries
  if [ -f "ai/progress.log" ]; then
    echo ""
    echo "Recent Progress:"
    tail -5 ai/progress.log
  fi
}

# Help
show_help() {
  echo "Usage: ./ai/init.sh <command> [options]"
  echo ""
  echo "Commands:"
  echo "  bootstrap           Install dependencies"
  echo "  dev                 Start development server"
  echo "  check [options]     Run all checks (tests, types, lint, build, e2e)"
  echo "    --quick           Run only unit tests + E2E by E2E_TAGS (or @smoke)"
  echo "    --full            Run all tests including full E2E suite"
  echo "    --skip-e2e        Skip E2E tests entirely (unit tests only)"
  echo "  build               Build for production"
  echo "  status              Show project status"
  echo "  help                Show this help message"
  echo ""
  echo "Environment:"
  echo "  E2E_TAGS            Tags for E2E filtering in quick mode (e.g., @feature-auth)"
}

# Main entry point
case "${1:-help}" in
  bootstrap)
    bootstrap
    ;;
  dev)
    dev
    ;;
  check)
    shift
    check "$@"
    ;;
  build)
    build
    ;;
  status)
    status
    ;;
  help|--help|-h)
    show_help
    ;;
  *)
    log_error "Unknown command: $1"
    show_help
    exit 1
    ;;
esac
